### ISSUE TITLE
Is vCluster supporting eBPF?

### ISSUE THREAD

**Issue by batistein** [loft-sh/vcluster#210] opened 2021-11-29 08:17 UTC
First of all great product!
After some testing I just wanted to ask if vCluster is natively supporting ebpf and a kube-proxy free environment?

**Comment by FabianKramm** [comment] 2021-11-29 08:31
@batistein thanks for creating this PR! I don't see why vcluster wouldn't support these as networking is not virtualized at all and pods use the host network for communication.

**Comment by batistein** [comment] 2021-11-29 08:36
@FabianKramm Thank you very much! I recently had some issues with istio and cilium ebpf which were not directly apparent since 99% of all use-cases worked... that's why i wanted to ask beforehand if there is anything that speaks against it from a design architecture point of view.

**Comment by matskiv** [comment] 2022-10-14 14:07
This seems to be answered, so I am closing the issue.
P.S: AFAIK we have not had any reports about issues caused by eBPF :)

**Closed by matskiv** 2022-10-14 14:07 UTC
Labels: area/syncer, kind/question
