### ISSUE TITLE
Vcluster list command

### ISSUE THREAD

**Issue by harshsing2891** [loft-sh/vcluster#875] opened 2022-12-27 10:36 UTC
### What happened?

Vcluster list output reveals details of all vcluster...is there anyway we can remove or hide this command . If I am using rbac to block this command but what is happening vcluster connect command also getting blocked.

Pls help

### What did you expect to happen?

Only admin can see vcluster details using vcluster list command

### How can we reproduce it (as minimally and precisely as possible)?

Vcluster list command

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
```

</details>
1\.22

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>
1\.22

### vlcuster version

<details>

```
$ vcluster --version
# paste output here
```

</details>
K3s 1.25

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>
K3s

### OS and Arch

<details>

```
OS: 
Arch:
```

</details>
Ubuntu

**Comment by matskiv** [comment] 2022-12-27 11:03
This seems like a duplicate of #874 - please close one of your issues. We will answer the issue as soon as we have time to do so.

**Comment by FabianKramm** [comment] 2023-01-10 09:12
Hello @harshsing2891! Would interesting to hear your use case for this, as the vcluster cli is just showing what it has access to. If you don't want vcluster cli to list vclusters, make sure the user doesn't has access to the host cluster itself

**Comment by harshsing2891** [comment] 2023-01-10 12:05
Hi Fabian
Thanks for the response

In my environment we have rbac user for example: developers

So our requirement is developers should not access vcluster of other developers

But vcluster list giving info of vcluster name and namespace..hence they r able to connect others vcluster as well.

I want only admin to have access of the output of vcluster list..
May be it seems wierd to u but this is the requirement

Thanks for developing such a useful tool🙏

**Comment by harshsing2891** [comment] 2023-01-10 12:11
And problem is when we r removing/modify rbac roles to block output of vcluster list ...

It is also impacting vcluster connect command as well.

**Comment by alexandradragodan** [comment] 2023-10-12 13:50
Hey, @harshsing2891 

Thanks for your request here. 
We have not seen this feature as a common use case for the invidual OSS developer, so this is now possible with vCluster.Pro. You can check that out [here](https://www.vcluster.com/pro/).

**Comment by alexandradragodan** [comment] 2023-10-12 13:50
Hey, @harshsing2891 

Thanks for your request here. 
We have not seen this feature as a common use case for the invidual OSS developer, so this is now possible with vCluster.Pro. You can check that out [here](https://www.vcluster.com/pro/).

**Closed by alexandradragodan** 2023-10-12 13:50 UTC
Labels: kind/bug, bug
