### ISSUE TITLE
Vcluster CLI Page Crashed 

### ISSUE THREAD

**Issue by kelvinparmar** [loft-sh/vcluster#1153] opened 2023-08-12 03:14 UTC
### What happened?

when I am going to download vcluster cli for windows or any versions sometime it's going crashed. I don't know it's only happing with me or this is an isssue.

<img width="960" alt="Screenshot 2023-08-11 213659" src="https://github.com/loft-sh/vcluster/assets/94775043/6148d34f-0724-4a2d-9536-54e5c1a1a961">

### What did you expect to happen?

It will direct go to the installtions page 

<img width="959" alt="Screenshot 2023-08-11 213805" src="https://github.com/loft-sh/vcluster/assets/94775043/069511bb-48e6-4b0d-9998-5c6e0d9f2c1c">

### How can we reproduce it (as minimally and precisely as possible)?

<img width="959" alt="Screenshot 2023-08-11 213805" src="https://github.com/loft-sh/vcluster/assets/94775043/8b094535-87f0-49ae-ace8-cf5f0dd061a5">

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
# paste output here
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# Write here
```

</details>

### OS and Arch

<details>

```
OS: 
Arch:
```
</details>

**Comment by ishankhare07** [comment] 2023-08-14 10:02
duplicate of #1111

**Comment by kelvinparmar** [comment] 2023-08-14 10:13
@ishankhare07 IDK about it. should I remove this issue?

**Closed** 2023-08-22 11:09 UTC
Labels: kind/bug
