### ISSUE TITLE
ELK does not work as expected in host cluster

### ISSUE THREAD

**Issue by vumdao** [loft-sh/vcluster#594] opened 2022-07-12 17:37 UTC
### What happened?

I installed Elasticsearch on the host and what I got from search is following and it shows nothing related to kubernetes labels/namespace
![image](https://user-images.githubusercontent.com/37215642/178556455-b951bce8-c16b-4105-b37d-3175c5fae940.png)

Here is labels and annotations of a pod
```
Labels:       vcluster.loft.sh/label-dev7-x-a172cedcae=app                         
              vcluster.loft.sh/label-dev7-x-fdcdfa3fd8=58fbbd664          
              vcluster.loft.sh/managed-by=dev7                                                           
              vcluster.loft.sh/namespace=default                                                         
              vcluster.loft.sh/ns-label-dev7-x-cf1227b7b2=default          
Annotations:  cluster-autoscaler.kubernetes.io/safe-to-evict: true         
              kubectl.kubernetes.io/restartedAt: 2022-07-05T17:28:31+07:00 
              kubernetes.io/psp: eks.privileged                                                          
              vcluster.loft.sh/labels:                                                                   
                app="app"                                                                                
                pod-template-hash="58fbbd664"                                                            
              vcluster.loft.sh/managed-annotations: kubectl.kubernetes.io/restartedAt                    
              vcluster.loft.sh/name: app-58fbbd664-4rll8                                         
              vcluster.loft.sh/namespace: default                                                                                                                                                                  
              vcluster.loft.sh/object-name: app-58fbbd664-4rll8                                                                                                                                                    
              vcluster.loft.sh/object-namespace: default                                                 
              vcluster.loft.sh/owner-set-kind: ReplicaSet                                                
              vcluster.loft.sh/service-account-name: default                                             
```

but the search result is nothing
![image](https://user-images.githubusercontent.com/37215642/178557228-0e8ade99-74c1-4a16-a375-10a642134550.png)

### What did you expect to happen?

Using ELK can search filter based on app labels and namespace

### How can we reproduce it (as minimally and precisely as possible)?

Install Elasticsearch on host cluster

### Host cluster Kubernetes version

EKS cluster v1.21

### Host cluster Kubernetes distribution

v1.21

### vlcuster version

vcluster version 0.8.1

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k8s

### OS and Arch

EKS/EC2

**Comment by matskiv** [comment] 2022-07-13 08:48
Closing since this is about the ELK instance installed in the host cluster. We can reopen if some evidence of vcluster being the root cause is provided.

**Closed by matskiv** 2022-07-13 08:48 UTC
Labels: kind/bug
