### ISSUE TITLE
vcluster compatibility issue with contour based ingress controller

### ISSUE THREAD

**Issue by chidambaranathan-r** [loft-sh/vcluster#858] opened 2022-12-13 13:23 UTC
### What happened?

While trying to use contour as cluster wide ingress controller in the host cluster, we could not create httproxy resource inside vcluster and we get the below error:
`error: unable to recognize "service1_httpproxy.yaml": no matches for kind "HTTPProxy" in version "projectcontour.io/v1"`

It looks like vcluster is unable to pickup the contour CRDs from the host cluster.

Please refer "How can we reproduce it (as minimally and precisely as possible)?" for more details.

### What did you expect to happen?

We expect, vcluster to able to expose application with httpproxy resource (with contour ingress controller in host cluster) as it works for ingress resource (with nginx ingress controller in host cluster).

### How can we reproduce it (as minimally and precisely as possible)?

It works as expected in nginx based ingress controller. Refer the file: nginx_vcluster.txt

It throws error in contour based ingress controller. Refer the file: contour_vcluster.txt

[nginx_vcluster.txt](https://github.com/loft-sh/vcluster/files/10218190/nginx_vcluster.txt)
[contour_vcluster.txt](https://github.com/loft-sh/vcluster/files/10218191/contour_vcluster.txt)

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.2", GitCommit:"092fbfbf53427de67cac1e9fa54aaa09a28371d7", GitTreeState:"clean", BuildDate:"2021-06-16T12:59:11Z", GoVersion:"go1.16.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.14", GitCommit:"0f77da5bd4809927e15d1658fb4aa8f13ad890a5", GitTreeState:"clean", BuildDate:"2022-06-15T14:11:36Z", GoVersion:"go1.16.15", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# v1.21.14
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.13.0
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
# k3s:v1.23.4-k3s1
```

</details>

### OS and Arch

<details>

```
Worker nodes detail -->
OS: Ubuntu 18.04.5 LTS
Arch: x86_64
```
</details>

**Comment by matskiv** [comment] 2022-12-13 13:38
Hello @chidambaranathan-r 
Out of the box, vcluster does not support CRDs that are not part of Kubernetes project.
But we have a plugin capability which can provide additional features, including support for some additional CRDs. This documentation page describes a generic CRD sync plugin that may be helpful for your use case - https://www.vcluster.com/docs/plugins/generic-crd-sync
and we have an example configuration for the Countours HTTPProxy CRD here in the plugin repo - https://github.com/loft-sh/vcluster-generic-crd-sync-plugin/blob/main/examples/contour/plugin.yaml Important note - this config is provided only as an example, with no guarantees.

I will close this issue as it is not a bug in vcluster. If you want to discuss the plugin I mentioned above feel free to join the vcluster channel in our Slack ( https://slack.loft.sh/ )  or create an issue in the plugins repo ( https://github.com/loft-sh/vcluster-generic-crd-sync-plugin )

**Closed by matskiv** 2022-12-13 13:38 UTC
Labels: kind/bug

**Comment by chidambaranathan-r** [comment] 2022-12-14 10:17
Thanks @matskiv for the pointers. It was really helpful and we were able to make it work.
