### ISSUE TITLE
Deletion of namespace hangs when proxying metrics-server

### ISSUE THREAD

**Issue by trondvindenes-hvikt** [loft-sh/vcluster#1163] opened 2023-08-17 12:26 UTC
### What happened?

Installed a vcluster using helm chart vcluster-k8s-0.15.5.tgz. Enabled proxy for metrics-server.

I then connect to the vcluster, and try to delete a namespace, even if it's newly created and empty, this happens:
```
Name:         testing
Labels:       kubernetes.io/metadata.name=testing
Annotations:  <none>
Status:       Terminating
Conditions:
  Type                                         Status  LastTransitionTime               Reason                  Message
  ----                                         ------  ------------------               ------                  -------
  NamespaceDeletionDiscoveryFailure            True    Thu, 17 Aug 2023 13:58:06 +0200  DiscoveryFailed         Discovery failed for some groups, 1 failing: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server could not find the requested resource
  NamespaceDeletionGroupVersionParsingFailure  False   Thu, 17 Aug 2023 13:58:06 +0200  ParsedGroupVersions     All legacy kube types successfully parsed
  NamespaceDeletionContentFailure              False   Thu, 17 Aug 2023 13:58:06 +0200  ContentDeleted          All content successfully deleted, may be waiting on finalization
  NamespaceContentRemaining                    False   Thu, 17 Aug 2023 13:58:06 +0200  ContentRemoved          All content successfully removed
  NamespaceFinalizersRemaining                 False   Thu, 17 Aug 2023 13:58:06 +0200  ContentHasNoFinalizers  All content-preserving finalizers finished

No resource quota.

No LimitRange resource.
```

### What did you expect to happen?

That I should be able to delete the namespace without messing with namespace finalizers.

### How can we reproduce it (as minimally and precisely as possible)?

Install vcluster
`helm install vcluster vcluster-k8s-0.15.5.tgz -f values.yaml`

values.yaml:
```
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true

sync:
  nodes:
    enabled: true
    syncAllNodes: true
  ingresses:
    enabled: true

enableHA: true

syncer:
  image: ghcr.io/loft-sh/vcluster:0.15.5
  replicas: 3

etcd:
  image: registry.k8s.io/etcd:3.5.7-0
  replicas: 3

controller:
  image: registry.k8s.io/kube-controller-manager:v1.24.14
  replicas: 3

api:
  image: registry.k8s.io/kube-apiserver:v1.24.14
  replicas: 3

coredns:
  image: coredns/coredns:1.10.1
  replicas: 3

service:
  type: LoadBalancer
```

`vcluster connect vcluster`
`kubectl create ns testing`
`kubectl delete ns testing`

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:15:31Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10+vmware.1", GitCommit:"b980a736cbd2ac0c5f7ca793122fd4231f705889", GitTreeState:"clean", BuildDate:"2023-01-24T15:29:49Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
Tanzu Kubernetes Grid Integrated Edition 1.15.x
```
But it's not isolated to TKGI. Happens even in a Kubernetes Kind cluster.

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.15.5
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k8s
```

</details>

### OS and Arch

<details>

```
OS: Ubuntu Xenial
Arch: x64
```

When running in Kind:
```
OS: RHEL7
Arch: x64
```
</details>

**Comment by ishankhare07** [comment] 2023-08-28 10:40
Hi @trondvindenes-hvikt I tried reproducing your issues with the following vcluster values:
```yaml
proxy:
  metricsServer:
    nodes:
      enabled: true
    pods:
      enabled: true

sync:
  nodes:
    enabled: true
    syncAllNodes: true
  ingresses:
    enabled: true

enableHA: true

volumes:
  - name: data
    emptyDir: {}

syncer:
  image: ghcr.io/loft-sh/vcluster:0.15.5
  replicas: 3

etcd:
  image: registry.k8s.io/etcd:3.5.7-0
  replicas: 3

controller:
  image: registry.k8s.io/kube-controller-manager:v1.24.14
  replicas: 3

api:
  image: registry.k8s.io/kube-apiserver:v1.24.14
  replicas: 3

coredns:
  image: coredns/coredns:1.10.1
  replicas: 3
```

I can report that I have no issues creating or deleting namespaces inside vcluster. It can be specific to your host cluster environment.

Also can you try this with the latest `0.15.6` or `0.15.7` vcluster releases?

**Comment by trondvindenes-hvikt** [comment] 2023-09-04 06:45
I have tried with 0.15.6 and .7, same result. The same also happes in a kubeadm-deployed host cluster running on Rocky Linux in my home lab. 

To summarize, I experience this error in three different host cluster environments, all running Kubernetes 1.24.x
- TKGI cluster
- Kind cluster
- kubeadm-created cluster

I'm gonna do some more digging and testing. Just last week we upgraded our host clusters, I haven't had the chance to follow up on this since.

**Comment by trondvindenes-hvikt** [comment] 2023-09-19 21:32
I've also tested this using a host cluster on K8s version 1.25.10, still same issue. I've done some digging through the source code, and have come up with a theory. Not sure why I'm experiencing this and you are not.

As I understand it, when connected to a vcluster, kubectl is actually talking to the service vcluster-lb with the selector app=vcluster,release=vcluster. 
```
[trond@kube ansible-k8s]$ kubectl get pods -lapp=vcluster,release=vcluster
NAME                      READY   STATUS    RESTARTS   AGE
vcluster-64b7b874-5t2mj   1/1     Running   0          22d
vcluster-64b7b874-db6ng   1/1     Running   0          22d
vcluster-64b7b874-mdbg9   1/1     Running   0          22d
```

And the vcluster pods is propably forwarding most of the requests towards either the host cluster or the kube-api inside the vcluster.

So when proxying metrics server, vcluster is rewriting the requests and sending it to the host cluster metrics server. So far so good.

But when I'm attempting to delete a namespace, Kubernetes needs to check for all possible existing resources within that namespace, and it queries all the possible api-resources that can exist within that namespace. It is here the fault happens. kube-controller-manager is attempting to query the kube-apiserver in vcluster directly, and this does not know of an metrics-server, and returns 404:
```
default/vcluster-controller-758d964cf6-j2tdz[kube-controller-manager]: I0919 13:19:12.425734       1 round_trippers.go:553] GET https://vcluster-api:443/apis/metrics.k8s.io/v1beta1 404 Not Found in 1 milliseconds
```

I've managed to replicate the 404 by querying the api server:
```
kubectl port-forward svc/vcluster-api 4433:443

[trond@kube client]$ curl -k --cert client-certificate --key client-key --cacert certificate-authority https://127.0.0.1:4433/apis/metrics.k8s.io/v1beta1
404 page not found
```
When querying the vcluster-lb, I do get a result:
```
kubectl port-forward svc/vcluster-lb 4433:443

[trond@kube client]$ curl -k --cert client-certificate --key client-key --cacert certificate-authority https://127.0.0.1:4433/apis/metrics.k8s.io/v1beta1
{
  "kind": "APIResourceList",
  "apiVersion": "v1",
  "groupVersion": "metrics.k8s.io/v1beta1",
  "resources": [
    {
      "name": "nodes",
      "singularName": "",
      "namespaced": false,
      "kind": "NodeMetrics",
      "verbs": [
        "get",
        "list"
      ]
    },
    {
      "name": "pods",
      "singularName": "",
      "namespaced": true,
      "kind": "PodMetrics",
      "verbs": [
        "get",
        "list"
      ]
    }
  ]
}
```

Am I on to something here?

**Comment by ishankhare07** [comment] 2023-09-26 09:25
Hi @trondvindenes-hvikt , I have identified the issue. Its due to the syncer proxy and apiserver being deployed as separate components for the `k8s` and `eks` distros. You would not encounter this issue in single binary distros like `k3s` and `k0s`. Currently working on a fix for this and would be updated soon

**Comment by PavelGloba** [comment] 2023-10-20 15:16
I have the same issue with k8s vcluster distro

**Closed** 2023-11-15 12:40 UTC
Labels: kind/bug
