### ISSUE TITLE
VCluster don't work with Traefik IngressClass

### ISSUE THREAD

**Issue by mamu-reply** [loft-sh/vcluster#1634] opened 2024-03-28 16:55 UTC
### What happened?

I've defined as IngressClass in the VCluster ingress Traefik, but there is no way to work, i've configured it as documentation say, adding passthrough, but nothing happen and i see only "Internal Server Error".

### What did you expect to happen?

As Nginx that it can complete the connection for VCluster login

### How can we reproduce it (as minimally and precisely as possible)?

Create the VCluster with an ingress as this
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-letsencrypt-production-route53
  name: vcluster-1-ingress
  namespace: vcluster-1
spec:
  ingressClassName: traefik
  rules:
    - host: vcluster-1.example.com
      http:
        paths:
          - backend:
              service:
                name: vcluster-1
                port:
                  number: 443
            path: /
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - vcluster-1.example.com
      secretName: vcluster-1.example.com-tls
```
And this IngressRouteTCP for Traefik
```yaml
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: vcluster-1
  namespace: vcluster-1
  annotations:
    kubernetes.io/ingress.class: traefik
  labels:
      ingressclass: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`*`)
      services:
        - name: vcluster-1
          namespace: vcluster-1
          port: 443
  tls:
    passthrough: true

```

### Anything else we need to know?

Traefik is installed via Helm Chart v2.9.6  and VCluster is with helm 0.19.3

### Host cluster Kubernetes version

<details>

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4", GitCommit:"fa3d7990104d7c1f16943a67f11b154b71f6a132", GitTreeState:"clean", BuildDate:"2023-07-19T12:20:54Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"darwin/arm64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27+", GitVersion:"v1.27.11-eks-b9c9ed7", GitCommit:"f19f83c16ca534237fbfb65bc580d51752b98c91", GitTreeState:"clean", BuildDate:"2024-03-02T03:46:53Z", GoVersion:"go1.21.7", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
EKS at v1.27.11
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.19.3
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: MacOS
Arch: 
```
</details>

**Comment by johannesfrey** [comment] 2024-04-02 10:47
Hi @mamu-reply,

just to be sure we are on the same page:
- With `[...] as documentation say` you mean the docs of traefik not vcluster?
- With `[...] i see only "Internal Server Error"` you mean the log output of traefik?

Would it be possible for you to provide additional log messages in order to better pin down the cause. Ideally from traefik as well as from the vcluster pod?!
Furthermore, per default vcluster does **not** sync `ingresses` and `ingressclasses` (See following table: https://www.vcluster.com/docs/syncer/core_resources). Could you double check the values you used to start the vcluster.

**Comment by johannesfrey** [comment] 2024-04-18 08:43
Hey @mamu-reply, were you able to resolve the issue? If not, could you provide the values you used to configure your virtual cluster?

**Comment by johannesfrey** [comment] 2024-04-30 14:21
Closing for now. Feel free to re-open.

**Closed by johannesfrey** 2024-04-30 14:21 UTC
Labels: kind/bug, wait-on-user
