### ISSUE TITLE
Unable to connect to the server: authenticationrequired

### ISSUE THREAD

**Issue by ashishkamat2791** [loft-sh/vcluster#1344] opened 2023-11-02 07:22 UTC
I have created argo workflow by which I am creating vclusters which can be created succesfully using expose option, LBs are getting created properly
in side argo workflow I am using following to create vcluster
`vcluster create {{inputs.parameters.namespace}}-{{inputs.parameters.index}} -n {{inputs.parameters.namespace}} --connect=false  -f vcluster-values.yml --expose`
where as following parameters are getting passed from argo workflow inputs

{inputs.parameters.namespace}
{{inputs.parameters.index}}

I am creating dynamic kubeconfig file using following
`vcluster connect "{{inputs.parameters.namespace}}-{{inputs.parameters.index}}" -n "${namespace}" --update-current=false `

but with this kubeconfig file I am not able to add cluster to argocd and then deploy application in vcluser using argocd

following commands are getting used for same

- add cluster
`argocd cluster add <cluster-name> --kubeconfig=kubeconfig.yaml -y `
- deploy app
`argocd app create <app-name> --repo <git-repo-url> --path <path-for-app> --dest-name <vcluster-name> --dest-namespace <vcluster-namespace>`

not sure but same thing works fine if I run above two commands in local but giving authentication issue inside argo-workflow pods

My vcluster values.yaml as follows
```

defaultImageRegistry: <private-registry>
sync:
  nodes:
    enabled: true
    syncAllNodes: true
  serviceaccounts:
    enabled: true
fallbackHostDns: true
# Syncer configuration
syncer:
  # Image to use for the syncer
  image: loftsh/vcluster:0.15.7
  kubeConfigContextName: "vcluster-scale-test"
  serviceAnnotations: 
     <enterprise-annoatations>
  # extraArgs: {}
  resources:
    limits:
      cpu: 512m
      memory: 256Mi
    requests:
      # ensure that cpu/memory requests are high enough.
      # for example gke wants minimum 10m/32Mi here!
      cpu: 20m
      memory: 64Mi

# Virtual Cluster (k3s) configuration
vcluster:
  # Image to use for the virtual cluster
  image: rancher/k3s:v1.27.3-k3s1
  command:
    - /bin/k3s
  baseArgs:
    - server
    - --write-kubeconfig=/data/k3s-config/kube-config.yaml
    - --data-dir=/data
    - --disable=traefik,metrics-server,local-storage,coredns
 #  - --disable-network-policy
    - --disable-agent
 #   - --disable-cloud-controller
    - --flannel-backend=none
    - --kube-apiserver-arg=bind-address=127.0.0.1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi
  serviceAccount:
     name: cluster-admin-vcluster
  workloadServiceAccount:
     name: cluster-admin-vcluster
  rbac:
    clusterRole: 
       create: true
    role:
      create: true

# The amount of replicas to run the statefulset with
replicas: 1

# Extra Annotations for the stateful set
annotations: {}
podAnnotations: {}


# Configure the ingress resource that allows you to access the vcluster
# ingress:
#   # Enable ingress record generation
#   enabled: true
#   # Ingress path type
#   pathType: ImplementationSpecific
#   apiVersion: networking.k8s.io/v1
#   ingressClassName: ""
#   host: <host-name>
#   annotations:
#     cert-manager.io/private-key-rotation-policy: always
#     kubernetes.io/ingress.class: nginx
#     nginx.ingress.kubernetes.io/backend-protocol: HTTPS
#     nginx.ingress.kubernetes.io/ssl-passthrough: "true"
#     nginx.ingress.kubernetes.io/ssl-redirect: "true"
#   # Ingress TLS configuration
#   tls: 
#      - secretName: argo-vcluster-tls
#        hosts:
#          - <host-name>

# If enabled will deploy the coredns configmap
coredns:
  enabled: true
  replicas: 1
  image: coredns/coredns:1.10.1
  resources:
    limits:
      cpu: 512m
      memory: 120Mi
    requests:
      cpu: 3m
      memory: 16Mi

**Comment by FabianKramm** [comment] 2023-11-02 09:31
@ashishkamat2791 thanks for creating this issue! Does the generated kube config look correct? Does it have the load balancer IP as server?

**Comment by alexandradragodan** [comment] 2024-02-02 10:15
Hey @ashishkamat2791 
Thanks for bringing this up. 

We haven't yet been able to identify the root cause of the authentication issue you're facing here. 
Closing the issue for now, please feel free to re-open it when you can provide us more insights to help you debug there.

**Closed by alexandradragodan** 2024-02-02 10:15 UTC
