### ISSUE TITLE
add support for AWS IAM Role for Service Account

### ISSUE THREAD

**Issue by bouallaguimahdi** [loft-sh/vcluster#862] opened 2022-12-14 23:49 UTC
### Is your feature request related to a problem?

It will be beneficial for people who would like to run a vcluster on top of EKS to be able to use IAM Role for service Account in order to give access to pods running inside the vcluster to aws resources through service accounts and AWS OIDC.

### Which solution do you suggest?

Add support for IAM role for service account (IRSA) when deploying vcluster on top of AWS EKS

### Which alternative solutions exist?

*No response*

### Additional context

*No response*

**Comment by alexandradragodan** [comment] 2022-12-15 11:08
Hi, @bouallaguimahdi 👋 

thanks a lot for opening this issue! 
We appreciate your suggestion and will consider it in our products' planning. 

Keep you posted!

**Comment by FabianKramm** [comment] 2022-12-19 09:41
Hey @bouallaguimahdi ! This should be possible already with the [service account sync](https://www.vcluster.com/docs/architecture/synced-resources) in vcluster, would you mind trying this?

**Comment by matskiv** [comment] 2022-12-27 17:06
@bouallaguimahdi One way to make it work is with the service sync as mentioned above by Fabian. Just keep in mind that in your AWS role/policy you will need to reference the synced ServiceAccount name and the namespace of the vcluster in the host cluster.

**Comment by bouallaguimahdi** [comment] 2022-12-27 17:09
Hi @matskiv  and @FabianKramm,

I have just tested the synced service account and it works as a charm.
Thank you guys for your help.

**Comment by matskiv** [comment] 2022-12-27 17:15
Awesome! I retagged this as a question, and it seems like it is answered so I'll close it, but feel free to comment if you disagree :)

**Closed by matskiv** 2022-12-27 17:15 UTC
Labels: kind/question

**Comment by willjw1** [comment] 2023-10-24 18:14
@bouallaguimahdi I'm trying to do the same thing I think and cannot figure it out.  I have added serviceaccounts to be sync'd back to the host cluster. In my host cluster I'm naming the vcluster as "vcluster" and my namespace in the vcluster is called "external-secrets".  In my AWS Role's trust policy I've listed the ServiceAccount Name as "system:serviceaccount:vcluster:external-secrets-x-external-secrets-x-eaaswill" but within the log I'm seeing: "could not validate provider: WebIdentityErr: failed to retrieve credentials\ncaused by: InvalidIdentityToken: No OpenIDConnect provider found in your account for https://kubernetes.default.svc.cluster.local\n\tstatus code: 400

**Comment by matskiv** [comment] 2023-10-24 18:29
@willjw1 Please create a new issue, as I don't think many maintainers will see your comment here.
Specify which application is trying to use the token and link to the source code if it is open source.
My 2 cents - it seems like the app is trying to use the regular k8s SA token. IRSA should work if the app uses a token from the projected volume, the path to which is injected via an env var (I don't recall the name now, but it has AWS prefix AFAIK).

**Comment by willjw1** [comment] 2023-10-24 19:02
I raised: https://github.com/loft-sh/vcluster/issues/1275 but no one was assigned and I got no response.

**Comment by bouallaguimahdi** [comment] 2023-10-24 20:35
Hello @willjw1 I think you have miss configured your IAM role which should be used by your serviceaccount, have a look at these two references:
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
https://repost.aws/knowledge-center/eks-troubleshoot-oidc-and-irsa
That being said, I think you should have a trust policy that lokks like below:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::12312312312:oidc-provider/oidc.eks.eu-west-2.amazonaws.com/id/XXXXXXXXXXXXXXXXXX"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.eu-west-2.amazonaws.com/id/XXXXXXXXXXXXXXXXXX:aud": "sts.amazonaws.com",
                    "oidc.eks.eu-west-2.amazonaws.com/id/XXXXXXXXXXXXXXXXXX:sub": "system:serviceaccount:vcluster:external-secrets-x-external-secrets-x-vcluster"
                }
            }
        }
    ]
}

As you can see in the trust policy I've changed your serviceaccount mapping at the end (eaaswill -> vcluster) because I remember the mapping betwwen the vcluster and the host cluster service accounts is the following:

Service account name :

test-sa-x-kube-system-x-vc1  ==>

sa name-in-vcluster  (test-sa)
+ x  
+ namespace-in-vcluster  (kube-sstem)
+ x  
+ host-namespace  (vc1)

I hope this helps.

**Comment by willjw1** [comment] 2023-10-31 19:35
I thought it was:
host cluster:
vcluster           external-secrets-544ccdd989-xpnx8-x-external-secrets-x-eaaswill. (I think that is <pod within vcluster>-x-<namespace within vcluster>-<name of vcluster>)
vcluster:
external-secrets   external-secrets-544ccdd989-xpnx8

So how I interpret that it should be:

system:serviceaccount:<NAME of Namespace in host cluster>:<Name of pod as it is displayed in host cluster>
IE: 
system:serviceaccount:vcluster:external-secrets-544ccddxyz-xpnx8-x-external-secrets-x-eaaswill

I might be misunderstanding, so I've tried a few variations as you've suggested.  but none of them have given me the result I'm looking for.

**Comment by joebowbeer** [comment] 2023-10-31 20:24
@willjw1 ICYMI,

If service account sync is enabled and everything else defaulted, the (sync'd) service account in the underlying cluster that corresponds to the service account named SERVICEACCOUNT in the NAMESPACE namespace in the vcluster named VCLUSTERNAME is:

SERVICEACCOUNT-x-NAMESPACE-x-VCLUSTERNAME

HOWEVER, there is a 63 character maximum; if longer, the string is truncated and a -HASH is appended.

If you are matching roles with StringEqual, the condition string for the associated role would be:

system:serviceaccount:vcluster-VCLUSTERNAME:SERVICEACCOUNT-x-NAMESPACE-x-VCLUSTERNAME

**Comment by willjw1** [comment] 2023-11-02 13:34
ok, so I think I got a part of that confused.

system:serviceaccount:vcluster-VCLUSTERNAME:SERVICEACCOUNT-x-NAMESPACE-x-VCLUSTERNAME

so my vcluster's name is: vcluster
The service accounts's name is: external-secrets
The namespace is (within vlcuster) is: external-secrets
and the vcluster is called vcluster

so that's either:
system:serviceaccount:vcluster:external-secrets-x-external-secrets-x-vcluster"
or:
system:serviceaccount:vcluster-vcluster:external-secrets-x-external-secrets-x-vcluster"

both of which give me the same error.   I've experimented enough on this cluster, that I think I'll tear it down and start from scratch.  Then I'll try this all again.

**Comment by willjw1** [comment] 2023-11-03 17:28
ok so that didn't work either.

let's go over this again:
The sa on the host cluster which is used in the vcluster is called:

kubectl get sa -n vcluster external-secrets-x-external-secrets-x-eaaswill -o yaml

I have that set with my annotations:
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789999:role/eaaswill_external_secrets_role

within the role arn:aws:iam::123456789999:role/eaaswill_external_secrets_role I have for my trust relationship:
{
    "Version": "2012-10-17",
    "Statement": [
        {  # I'm including the first one here for completeness this connects my external secrets on the host cluster.
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::1234567899999:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/XYZ"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.us-east-1.amazonaws.com/id/XYZ:sub": "system:serviceaccount:external-secrets:secrets-manager"
                }
            }
        },
        { # this is the statement which I want to give access to the vcluster on.
            "Effect": "Allow",
            "Principal": {
                "Federated": "arn:aws:iam::1234567899999:oidc-provider/oidc.eks.us-east-1.amazonaws.com/id/XYZ"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringEquals": {
                    "oidc.eks.eu-west-2.amazonaws.com/id/XYZ:aud": "sts.amazonaws.com",
                    "oidc.eks.us-east-1.amazonaws.com/id/XYZ:sub": "system:serviceaccount:vcluster:external-secrets-x-external-secrets-x-eaaswill"
                }
            }
        }
    ]
}

**Comment by frank-bee** [comment] 2023-11-27 20:01
@willjw1 are you able to use IRSA meanwhile? 
Did not try this out myself yet but would be good to know.
There is an article from AWS which does not answer this clearly....

**Comment by frank-bee** [comment] 2023-12-01 01:56
For me IRSA works, tried it out with external secrets conteoller.
Would be nice to allow adding IRSA role annotation to the SA in the vcluater

**Comment by joebowbeer** [comment] 2023-12-01 02:26
@frank-bee The IRSA annotation on service accounts in the vcluster have been working for a year:

https://github.com/loft-sh/vcluster/issues/862#issuecomment-1357366039

Please open a new issue of there is something left to do.

**Comment by joebowbeer** [comment] 2023-12-01 02:30
@willjw1 In my experience, you might receive more help in the Slack channel.

> I raised: #1275 but no one was assigned and I got no response.

**Comment by frank-bee** [comment] 2023-12-01 03:02
@joebowbeer what I meant, is direct support of IRSA in the vcluater. Otherwise there is still some logic required when creating the roles in AWS.

you anyway use the EkS Anywhere distribution in vcluater. Should he possible to configure OIDC there I assume.
Did not find much docu for the eks helm chart of vcluater, is there some blog at least?
