### ISSUE TITLE
Incorrect KUBERNETES_SERVICE_HOST set on Pod Env Variables

### ISSUE THREAD

**Issue by donmstewart** [loft-sh/vcluster#1687] opened 2024-04-15 20:59 UTC
### What happened?

Backup the vCluster namespace on the Host Kubernetes Cluster. 

Delete the namespace 

Restore the vCluster and the restored pods try to start immediately, however, the new pods have/get the old ENV vars on the pods for `KUBERNETES_SERVICE_HOST` and fail due to not being able to talk to the API server in new vCluster. 

A manual delete of the pods causes the POD to get the new ENV set and the Pod works.

### What did you expect to happen?

The Pods to start correctly with the new API Server address.

### How can we reproduce it (as minimally and precisely as possible)?

- Create a vCluster. 
- Backup the vCluster namespace on the host with Velero.
- Delete the vCluster namespace.
- Restore the namespace with Velero. 

Pods fail to start.

### Host cluster Kubernetes version

Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.0", GitCommit:"a866cbe2e5bbaa01cfd5e969aa3e033f3282a8a2", GitTreeState:"clean", BuildDate:"2022-08-23T17:44:59Z", GoVersion:"go1.19", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.3+k3s1", GitCommit:"f2585c1671b31b4b34bddbb3bf4e7d69662b0821", GitTreeState:"clean", BuildDate:"2022-10-25T19:59:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

### Host cluster Kubernetes distribution

AWS EKS

### vlcuster version

0.16.0

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

k3s

### OS and Arch

OS: Linux
Arch: AMD64

**Comment by johannesfrey** [comment] 2024-04-17 12:34
Hi @donmstewart thanks for creating this issue.

I tried to reproduce this with a minimal configuration locally one time using the vcluster version you are using as well (0.16.0) and once using the current stable version (0.19.5): Creating a virtual cluster on one host cluster, creating a backup, restoring the virtual cluster on another host cluster.

With 0.16.0 the syncer indeed logs the following (and the internal coredns being stuck in pending):
```
Reconciler error Service "kubernetes" is invalid: spec.clusterIPs: Invalid value: []string{"10.96.159.251"}: failed to allocate IP 10.96.1 59.251: the provided IP (10.96.159.251) is not in the valid range. The range of valid IPs is 192.168.194.128/25

Reconciler error waiting for DNS service IP
```

With 0.19.5 there are no errors and the virtual cluster as well as coredns come up fine. So I would suggest, if feasible, to upgrade vcluster to 0.19.5.

**Comment by johannesfrey** [comment] 2024-04-19 05:39
> _plugin.tpl

Hm, that is really strange because you have Helm 3.14.4 installed. Only Helm >= 3.10 understands continue and break. See: https://github.com/loft-sh/vcluster/issues/1654#issuecomment-2040240385
How did you upgrade the chart and, sorry for asking the obvious, the helm version you posted is on the same machine from where you upgraded your virtual cluster?

**Comment by donmstewart** [comment] 2024-04-19 20:47
We found the issue thanks for responding. We now have a vcluster provisioned.

That said the config yaml is totally different especially some flags that we got added such as 

```
sync:
  pods:
    # Sync readiness gates to host cluster
    status: true
```

Is this now defaulted to happen or no longer possible ? Without this we are dead in the water.

**Comment by donmstewart** [comment] 2024-04-20 01:22
We got past abd are running 0.19.5 but have the same issue with the KUBERNETES_SERIVE_HOST being incorrect.

**Comment by johannesfrey** [comment] 2024-04-23 05:39
Hey @donmstewart
So it's not about the virtual cluster pods themselves (syncer) but about pods that are/were running inside a virtual cluster. Sorry, I totally got this wrong. I'll take another look. In the meantime, are there any similarities between the pods that have an incorrect KUBERNETES_SERVICE_HOST?

**Comment by donmstewart** [comment] 2024-04-23 14:00
Correct it's the pods within the vCluster not on the 'host' cluster. As to similarities nothing that comes to mind. Some are standard things like cert manager, external-dns, nginx that fail as well as our own app. Other things work with no noticeable reason why.

I was wondering if it's a timing issue of some sort. Restart any of the pods manually and they work fine.

**Comment by donmstewart** [comment] 2024-04-24 09:13
@johannesfrey Update above.

**Comment by johannesfrey** [comment] 2024-04-24 10:15
@donmstewart Thx. Just to be sure that we are on the same pager here as well. Velero is running on your host cluster and backups the whole namespace of the virtual cluster (vcluster pods themselves and all other pods that have been created inside that vcluster).

**Comment by johannesfrey** [comment] 2024-04-30 13:20
@donmstewart Were you able to test?

**Comment by donmstewart** [comment] 2024-05-01 09:34
@johannesfrey We were testing yesterday.  It seems so far that if we exclude pods and include all other resources we might indeed be okay as the pods are spun up from the Deployment/StatefulSets etc. so the pods are "new" and get the correct API server. 

This means we did not backup the vcluster pod but are relying on the vcluster statefulset on restore which I hope is okay. 

Need a few more testing cycles to be sure one way or the other.

**Comment by johannesfrey** [comment] 2024-05-03 06:18
@donmstewart Sounds good! I'll close this issue for now, but feel free to re-open if there are any issues left.

**Closed by johannesfrey** 2024-05-03 06:18 UTC
Labels: kind/bug, wait-on-user
