### ISSUE TITLE
Error syncing to physical cluster / Forbidden: seccomp may not be set

### ISSUE THREAD

**Issue by echo-devnull** [loft-sh/vcluster#1106] opened 2023-07-03 12:52 UTC
### What happened?

So I installed a standard/default `vcluster` in a 1.24 rancher cluster.

and then we tried to install a flux2 installation. But all of those pods get rejected:

```
Warning  SyncError  2m31s (x17 over 7m59s)  pod-syncer  Error syncing to physical cluster: pods "source-controller-7ff676964b-rscm2-x-flux-system-x-flux-maandag" is forbidden: PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]: Forbidden: seccomp may not be set]
```

We have already opened up the psp on the host cluster, but I'm having trouble understanding where I need to be to get this working.

Where do I need to add rights, and also, what rights  ;-)  ?

### What did you expect to happen?

To get the fluxcd pods running ;-)

### How can we reproduce it (as minimally and precisely as possible)?

RKE1 type rancher cluster and add a new vcluster inside of it.

Move the namespace to a rancher project with a "unrestriced" psp.

Pods from flux are not allowed to run after a `bootstrap` with that solution.

### Anything else we need to know?

*No response*

### Host cluster Kubernetes version

<details>

```
❯ k version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.3", GitCommit:"aef86a93758dc3cb2c658dd9657ab4ad4afc21cb", GitTreeState:"clean", BuildDate:"2022-07-13T14:30:46Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.10", GitCommit:"5c1d2d4295f9b4eb12bfbf6429fdf989f2ca8a02", GitTreeState:"clean", BuildDate:"2023-01-18T19:08:10Z", GoVersion:"go1.19.5", Compiler:"gc", Platform:"linux/amd64"}
```

</details>

### Host cluster Kubernetes distribution

<details>

```
# Write here
```

</details>

### vlcuster version

<details>

```
❯ vcluster --version
vcluster version 0.15.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
k3s
```

</details>

### OS and Arch

<details>

```
OS: flatcar linux
Arch: amd64
```

</details>

**Comment by rohantmp** [comment] 2023-07-04 07:16
Hi! Thanks for creating an issue! This error comes because the host cluster's PSP is rejecting the pod.  Once `[pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]` is settable, this error should disappear. I'm not too sure of the specific PSP settings needed to allow that field.

**Comment by rohantmp** [comment] 2023-07-04 07:21
> We have already opened up the psp on the host cluster, but I'm having trouble understanding where I need to be to get this working.

If the same error is appearing, it's still coming from the host cluster's PSP. Vcluster is just conveying the error it recieved when creating the pod on the host cluster. 

Closing because it seems clearly not to be a bug, but feel free to continue reopen if more info points at unexpected behavior in vcluster. Very much appreciate you opening the issue though!

**Closed by rohantmp** 2023-07-04 07:21 UTC
Labels: kind/bug, bug

**Comment by echo-devnull** [comment] 2023-07-04 07:30
It was indeed not a bug, but none of the other options would fit better ;-)

We had to add this to the namespace:
```yaml
---
# Create our own PSP
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    apparmor.security.alpha.kubernetes.io/pod: runtime/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
    serviceaccount.cluster.cattle.io/pod-security: unrestricted
<snipped>
```

Since PSP's are going the way of the dinosaur anyway, I see no point in adding it somewheere ;-)
