### ISSUE TITLE
Error: failed pre-install:timed out waiting for condition

### ISSUE THREAD

**Issue by skhota** [loft-sh/vcluster#613] opened 2022-07-20 14:13 UTC
### What happened?

New install of Vcluster fails/times out. Pl. see the attached logs. We have a successful install in the same VM/RHEL 7 host. But something happened last month and is not allowing us to create a new Vcluster.

### What did you expect to happen?

Should have a new cluster created.

### How can we reproduce it (as minimally and precisely as possible)?

Tried to create a new Vcluster but it times out.

### Anything else we need to know?

[vcluster-log.pdf](https://github.com/loft-sh/vcluster/files/9150574/vcluster-log.pdf)
[ssg-log.pdf](https://github.com/loft-sh/vcluster/files/9150587/ssg-log.pdf)

### Host cluster Kubernetes version

<details>

```
$ kubectl version
# paste output here
1.21.1

</details>


### Host cluster Kubernetes distribution

<details>
```

# Write here

```
1.21. x
</details>


### vlcuster version

<details>

```console
$ vcluster --version
# paste output here
Vcluster 0.7.0 and 0.10.2

</details>


### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>
```

# Write here

```

</details>
K8s

### OS and Arch

<details>
```

OS:
Arch:
RHEL 7
</details>

**Comment by skhota** [comment] 2022-07-20 15:15
Can you check if the vc10-1-jobKubernetes Job reported a successful status?

Ans: The status of the job is in vcluster-log.pdf attached in the ticket.

Thanks,
Susanta Hota.

________________________________

**Comment by matskiv** [comment] 2022-07-20 17:47
If you can reproduce pre-install error issue, please try installing vcluster with helm ([see "helm" tab in this doc](https://www.vcluster.com/docs/getting-started/deployment)) and run helm install it with `--debug` flag. If the issue is reproduced please attach logs as a text file or a link to a gist.

**Comment by skhota** [comment] 2022-07-21 14:50
Pl. see the attached for the helm debug log
[Helm-debug-log.pdf](https://github.com/loft-sh/vcluster/files/9160311/Helm-debug-log.pdf)
s

**Comment by matskiv** [comment] 2022-07-21 18:18
Unfortunately, you can not run helm by copying the command that was printed by vcluster.
Please follow the instructions on the helm tab on this docs page to run it correctly - https://www.vcluster.com/docs/getting-started/deployment

**Comment by skhota** [comment] 2022-07-22 13:40
I am running into the below error when trying to run the command, can you help. Not sure whats wrong I'm doing:
helm upgrade --install skh-1 \ 
--values vcluster1/vcluster/charts/k8s/vcluster.yaml \
--repo vcluster1/vcluster/charts/k8s/ \  
--namespace vc-test \
--repository-config=''
Release "skh-1" does not exist. Installing it now.
Error: failed to download "" (hint: running `helm repo update` may help)
zsh: command not found: --values
zsh: command not found: --repo
zsh: command not found: --namespace
zsh: command not found: --repository-config=

**Comment by skhota** [comment] 2022-07-22 13:43
Also tried this command:
helm upgrade --install skh-1 --values vcluster1/vcluster/charts/k8s/vcluster.yaml --repo vcluster1/vcluster/charts/k8s/ --namespace vc-test --repository-config=''
Error: "helm upgrade" requires 2 arguments
Not sure whats wrong.

**Comment by FabianKramm** [comment] 2022-07-22 16:07
@skhota try running:
```
helm upgrade skh-1 vcluster --install --create-namespace --values vcluster1/vcluster/charts/k8s/vcluster.yaml --repo https://charts.loft.sh --namespace vc-test --repository-config=''
```

Also make sure there is no folder / file called helm inside the directory you run this command

**Comment by skhota** [comment] 2022-07-26 15:34
Pl. see the attached for the Helm debug logs:
[Helm-debug-logs.pdf](https://github.com/loft-sh/vcluster/files/9191168/Helm-debug-logs.pdf)

**Comment by skhota** [comment] 2022-07-28 13:06
Hello, Can someone please help me on this issue.

**Comment by FabianKramm** [comment] 2022-07-28 17:14
@skhota mhh the logs look good, weird that the helm command times out even though the job is completed. What helm version do you have installed? You maybe need to upgrade helm itself. Also what happens if you increase the timeout to `--timeout 10m`? Besides that have you tried to use another distribution like k3s (just do `vcluster create my-vcluster`) or is there a specific reason you want to use k8s?

**Comment by skhota** [comment] 2022-07-28 19:32
I have installed successfully vcluster in the same environment in the past, not sure why its giving me this issue. K8s is the chosen distribution for our production. I can try upgrade Helm and test the install as you have asked. Will try increase the timeout to 10m and see what happens. Is there any other testing we can do to debug. What should happen in the next step after the job part runs successfully?

**Comment by skhota** [comment] 2022-07-29 14:37
Hi, I tried different Helm version but no change same issue. Can someone help.

**Comment by skhota** [comment] 2022-08-01 14:12
Anyone who can help me on this please.

**Comment by FabianKramm** [comment] 2022-08-01 15:54
@skhota if the job runs through correctly, helm should deploy vcluster itself, can you deploy vcluster correctly into a different cluster or does it fail in all of them?

**Comment by matskiv** [comment] 2022-10-14 12:51
This issue has had no reply for over 2 months. Closing.

**Closed by matskiv** 2022-10-14 12:51 UTC
Labels: kind/bug
