### ISSUE TITLE
No clear message when wrongly trying to use helm2 instead of helm3

### ISSUE THREAD

**Issue by vsantos** [loft-sh/vcluster#803] opened 2022-10-31 22:37 UTC
### What happened?

When trying to bootstrap a virtual cluster via `helm2` I ended up with a fatal error with no clarification. I'm assuming that the problem itself relies on `helm2` because changing to `helm3` apparently fixed the issue.

> ➜  ~ vcluster create test --namespace test --debug
> fatal  exit status 1

### What did you expect to happen?

I expect to have a clear message when wrongly using `helm2` (`v2.17.0`) instead of `helm3` and even the `--debug` flag was not enough to clarify the error. Example:

> ➜  ~ vcluster create test --namespace test --debug
> fatal  expected helm 3+ instead of helm 2

### How can we reproduce it (as minimally and precisely as possible)?

Try to create a virtual cluster using `helm2` by using the following command:

> vcluster create test --namespace test

### Anything else we need to know?

I still have some scenarios when I need to use `helm2` locally. I'm pretty new to platform services development so I'm wondering if is there any way I can try to fix this minor bug by myself. I think that could be an excellent first issue to start with and learn open-source processes if you folks think is something worth it.

### Host cluster Kubernetes version

<details>

```console
$ kubectl version

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-05-19T20:14:45Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/arm64"}
WARNING: version difference between client (1.23) and server (1.20) exceeds the supported minor version skew of +/-1
```

</details>

### Host cluster Kubernetes distribution

<details>

```
v1.23.6
```

</details>

### vlcuster version

<details>

```console
$ vcluster --version
vcluster version 0.12.2
```

</details>

### Vcluster Kubernetes distribution(k3s(default)), k8s, k0s)

<details>

```
kind v0.11.1 go1.16.4 darwin/amd64
```

</details>

### OS and Arch

<details>

```
OS:  darwin
Arch: intel arm64
```
</details>

**Comment by FabianKramm** [comment] 2022-11-01 10:24
@vsantos thanks for the issue! Yes we should improve the error message there or atleast be a little bit more verbose in what went wrong.

**Comment by matskiv** [comment] 2022-11-01 10:41
@vsantos Thank you for reporting the issue. We will be very happy to receive a PR for this, and I can help you with it if necessary. You can reach out for help via [our Slack instance](https://slack.loft.sh/) too, either #vcluster channel or feel free to PM me. So can I assign this issue to you then? :slightly_smiling_face: 

**Details about the root cause:**
The [/cmd/vclusterctl/cmd/create.go](https://github.com/loft-sh/vcluster/blob/main/cmd/vclusterctl/cmd/create.go) file contains the logic for `vcluster create` command. The [`func (cmd *CreateCmd) Run(args []string) error`](https://github.com/loft-sh/vcluster/blob/74ac1af61f884dc46ef14e66f1b203c05ed80aeb/cmd/vclusterctl/cmd/create.go#L129) gets called after the arguments are processed. I think in your case it then fails a couple of lines into the Run function when `exec.Command(helmBinaryPath, "version").CombinedOutput()` returns an error. You can verify by running `helm version` in your terminal and then checking the exit code (`echo $?`). So if it fails on this step we can return a custom error with a helpful message, e.g. `Please ensure that the "helm" binary in your PATH is valid. Only Helm v3 is supported.`
But if the `helm version` doesn't return an error then it will fail later:
```
...
fatal  error executing helm upgrade test https://charts.loft.sh/charts/vcluster-0.12.2.tgz --kubeconfig /tmp/164012950 --namespace test --install --repository-config='' --values /tmp/509748493: Error: unknown flag: --repository-config
```
so I think we should check the output of the `exec.Command(helmBinaryPath, "version").CombinedOutput()` too, and return an error if it isn't v3.

Also, the same changes should be applied to [the delete function](https://github.com/loft-sh/vcluster/blob/main/cmd/vclusterctl/cmd/delete.go#L80-L83), so it probably makes sense to put this logic into the `/cmd/vclusterctl/cmd/util.go` and call from both places.

**Closed** 2022-11-03 12:15 UTC
Labels: good first issue, area/cli, kind/bug
